export enum TypePropertyEnum {
  PARCEL = 'PARCEL',
  HOUSE = 'HOUSE',
  VILLA = 'VILLA',
  STUDIO = 'STUDIO',
  APARTMENT = 'APARTMENT',
  APARTMENT_FURNITURE = 'APARTMENT_FURNITURE',
  OFFICE = 'OFFICE',
  BUILDING = 'BUILDING',
  SHOP = 'SHOP',
  STORE = 'STORE',
}
