@baseUrl = http://localhost:3000

### CREATE 
POST {{baseUrl}}/products
Content-Type: application/json
  
  {
      "name": "Chaise",
      "description": "Chaise en bois",
      "price": "100",
      "categories": [
        { "id": 1 }
      ]
  }


### GET ALL
GET {{baseUrl}}/products

### GET ONE
GET {{baseUrl}}/products/1

### UPDATE
PATCH {{baseUrl}}/products/1
Content-Type: application/json

{
    "name": "David"
}

### DELETE

DELETE {{baseUrl}}/products/1

### UPLOAD

POST http://localhost:3000/products/1/upload
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJpYXQiOjE3MzMzNTExMDgsImV4cCI6MTczMzk1NTkwOH0.sOQBb2Pk1-9WUcmH0NkHBLyx5pznT-Q-otmVtbXYAwU
Content-Type: multipart/form-data

files=@/
name=test
description=test
price=100
location={"latitude":1.02,"longitude":1.05}
