services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - locapay_uploads:/app/upload
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: locapay
      POSTGRES_PASSWORD: YgWsW9ScFtWECh3yx8SX8K
      POSTGRES_DB: locapay
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  locapay_uploads:

