services:
  database:
    image: postgres
    restart: always
    ports:
      - "${DATASOURCE_PORT}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: postgres