@baseUrl = http://localhost:3000

### CREATE 
POST {{baseUrl}}/users
Content-Type: application/json
  
  {
      "name": "John Doe",
      "email": "johndoe@mail.com",
      "phone": "22996135159",
      "password": "Julianosis1234*"
  }

### GET ALL
GET {{baseUrl}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4Y2JjNmFkMC1iNmExLTQyOTEtOGI4ZS00ZWUzZjYzZWQ4NzMiLCJpYXQiOjE3MzI2NDY3MzIsImV4cCI6MTczMzI1MTUzMn0.ZYoLn7z30f1M-OYQYbopkYGDT67S0F6JHgPYgZHGU_A

### GET ONE
GET {{baseUrl}}/users/8cbc6ad0-b6a1-4291-8b8e-4ee3f63ed873
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4Y2JjNmFkMC1iNmExLTQyOTEtOGI4ZS00ZWUzZjYzZWQ4NzMiLCJpYXQiOjE3MzI2NDY3MzIsImV4cCI6MTczMzI1MTUzMn0.ZYoLn7z30f1M-OYQYbopkYGDT67S0F6JHgPYgZHGU_A

### UPDATE
PATCH {{baseUrl}}/users/8cbc6ad0-b6a1-4291-8b8e-4ee3f63ed873
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4Y2JjNmFkMC1iNmExLTQyOTEtOGI4ZS00ZWUzZjYzZWQ4NzMiLCJpYXQiOjE3MzI2NDY3MzIsImV4cCI6MTczMzI1MTUzMn0.ZYoLn7z30f1M-OYQYbopkYGDT67S0F6JHgPYgZHGU_A
Content-Type: application/json

{
    "name": "John"
}

### DELETE or SOFT DELETE

DELETE {{baseUrl}}/users/1
Content-Type: application/json

{
    "soft": true
}

### RECOVER SOFT DELETE
PATCH {{baseUrl}}/users/1/recover

