@baseUrl = http://localhost:3000

### CREATE 
POST {{baseUrl}}/users
Content-Type: application/json
  
  {
      "name": "John Doe",
      "email": "johndoe@mail.com",
      "phone": "22996135159",
      "password": "Julianosis1234*"
  }

### GET ALL
GET {{baseUrl}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMjc1MTUxNiwiZXhwIjoxNzMzMzU2MzE2fQ.-Qt5EnYdz8TMAbU1dIPWsDVP8HCS1n75EffUyenJb1Y

### GET ONE
GET {{baseUrl}}/users/25
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMjc1MTUxNiwiZXhwIjoxNzMzMzU2MzE2fQ.-Qt5EnYdz8TMAbU1dIPWsDVP8HCS1n75EffUyenJb1Y

### UPDATE
PATCH {{baseUrl}}/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMjc1MTUxNiwiZXhwIjoxNzMzMzU2MzE2fQ.-Qt5EnYdz8TMAbU1dIPWsDVP8HCS1n75EffUyenJb1Y
Content-Type: application/json

{
    "name": "John"
}

### DELETE or SOFT DELETE

DELETE {{baseUrl}}/users/1
Content-Type: application/json

{
    "soft": true
}

### RECOVER SOFT DELETE
PATCH {{baseUrl}}/users/1/recover

