@baseUrl = http://localhost:3000


### GET ALL
GET {{baseUrl}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMzIyNDYzMywiZXhwIjoxNzMzODI5NDMzfQ.2BfvjFu0bwFjqS8II9XOk6sGuF0hQWzuO43PjwLA5yc

### GET ONE
GET {{baseUrl}}/users/25
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMzIyNDYzMywiZXhwIjoxNzMzODI5NDMzfQ.2BfvjFu0bwFjqS8II9XOk6sGuF0hQWzuO43PjwLA5yc

### UPDATE
PATCH {{baseUrl}}/users/25
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMzIyNDYzMywiZXhwIjoxNzMzODI5NDMzfQ.2BfvjFu0bwFjqS8II9XOk6sGuF0hQWzuO43PjwLA5yc
Content-Type: application/json

{
    "name": "John"
}

### DELETE or SOFT DELETE
DELETE {{baseUrl}}/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMzIyNDYzMywiZXhwIjoxNzMzODI5NDMzfQ.2BfvjFu0bwFjqS8II9XOk6sGuF0hQWzuO43PjwLA5yc
Content-Type: application/json

{
    "soft": true
}

### RECOVER SOFT DELETE
PATCH {{baseUrl}}/users/1/recover

