@baseUrl = http://localhost:3000

### GET ALL
GET {{baseUrl}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImlhdCI6MTczMzIzMDAxNCwiZXhwIjoxNzMzODM0ODE0fQ.0jkT4FdQDDYKLczvcSh7RU3V0bsmErgp_5p9lbKKfNA

### GET ONE
GET {{baseUrl}}/users/25
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImlhdCI6MTczMzIzMDAxNCwiZXhwIjoxNzMzODM0ODE0fQ.0jkT4FdQDDYKLczvcSh7RU3V0bsmErgp_5p9lbKKfNA

### UPDATE
PATCH {{baseUrl}}/users/25
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImlhdCI6MTczMzIzMDAxNCwiZXhwIjoxNzMzODM0ODE0fQ.0jkT4FdQDDYKLczvcSh7RU3V0bsmErgp_5p9lbKKfNA
Content-Type: application/json

{
    "name": "John"
}

### DELETE or SOFT DELETE
DELETE {{baseUrl}}/users/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImlhdCI6MTczMzIzMDAxNCwiZXhwIjoxNzMzODM0ODE0fQ.0jkT4FdQDDYKLczvcSh7RU3V0bsmErgp_5p9lbKKfNA
Content-Type: application/json

{
    "soft": false
}

### RECOVER SOFT DELETE
PATCH {{baseUrl}}/users/1/recover

