@baseUrl = http://localhost:3000

### CREATE 
POST {{baseUrl}}/users
Content-Type: application/json
  
  {
      "name": "John Doe",
      "email": "johndoe@mail.com",
      "phone": "22996135159",
      "password": "123456"
  }

### GET ALL
GET {{baseUrl}}/users

### GET ONE
GET {{baseUrl}}/users/1

### UPDATE
PATCH {{baseUrl}}/users/1
Content-Type: application/json

{
    "name": "David"
}

### DELETE or SOFT DELETE

DELETE {{baseUrl}}/users/1
Content-Type: application/json

{
    "soft": true
}

### RECOVER SOFT DELETE
PATCH {{baseUrl}}/users/1/recover

