@baseUrl = http://localhost:3000

### CREATE 
POST {{baseUrl}}/users
Content-Type: application/json
  
  {
      "name": "John Doe",
      "email": "johnoll@mail.com",
      "phone": "22996135419",
      "password": "Julianosiss1234*"
  }

### GET ALL
GET {{baseUrl}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImlhdCI6MTczMzEyNzI4MCwiZXhwIjoxNzMzNzMyMDgwfQ.Ow28Jgp1OlgEtVDUuR8_aJjVdpWE2-3zrpkFgzUByDs

### GET ONE
GET {{baseUrl}}/users/25
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImlhdCI6MTczMzEyNzI4MCwiZXhwIjoxNzMzNzMyMDgwfQ.Ow28Jgp1OlgEtVDUuR8_aJjVdpWE2-3zrpkFgzUByDs

### UPDATE
PATCH {{baseUrl}}/users/25
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImlhdCI6MTczMzEyNzI4MCwiZXhwIjoxNzMzNzMyMDgwfQ.Ow28Jgp1OlgEtVDUuR8_aJjVdpWE2-3zrpkFgzUByDs
Content-Type: application/json

{
    "name": "John"
}

### DELETE or SOFT DELETE

DELETE {{baseUrl}}/users/1
Content-Type: application/json

{
    "soft": true
}

### RECOVER SOFT DELETE
PATCH {{baseUrl}}/users/1/recover

