@baseUrl = http://localhost:3000

### CREATE 
POST {{baseUrl}}/orders
Content-Type: application/json
  
  {
      "customer": { "id": 1 },
      "items": [
        { "product": { "id": 2 }, 
          "quantity": 2 
        }
      ]
  }


### GET ALL
GET {{baseUrl}}/orders

### GET ONE
GET {{baseUrl}}/orders/1

### UPDATE
PATCH {{baseUrl}}/orders/1
Content-Type: application/json

{
    "name": "David"
}

### DELETE

DELETE {{baseUrl}}/orders/1