@baseUrl = http://localhost:3000
@resource = auth

### REGISTER 
POST {{baseUrl}}/{{resource}}/register
Content-Type: application/json

  {
      "name": "Julian",
      "phone": "22955803035",
      "password": "Julianosis1234*",
      "password_confirmation": "Julianosis1234*"
  }

### VERIFY OTP
POST {{baseUrl}}/{{resource}}/verify_otp
Content-Type: application/json

  {
      "phone": "22955803035",
      "otp": 813574
  }

### LOGIN 
POST {{baseUrl}}/{{resource}}/login
Content-Type: application/json
  
  {
      "phone": "22955803035",
      "password": "Julianosis1234*"
  }


### FORGOT PASSWORD 
POST {{baseUrl}}/{{resource}}/forgot_password
Content-Type: application/json
  
  {
      "phone": "22955803035"
  }


### RESET PASSWORD 
POST {{baseUrl}}/{{resource}}/reset_password
Content-Type: application/json
  
  {
      "phone": "22955803035",
      "otp": 813574,
      "password": "Julianosis1234*",
      "password_confirmation": "Julianosis1234*"
  }


### GET PROFILE
GET {{baseUrl}}/{{resource}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEzLCJpYXQiOjE3MzMyMzk1MjcsImV4cCI6MTczMzg0NDMyN30.K6Ktqaq-iyqnX_SO9i4NwD4sbEVGArnRRuM24J44tgM
Content-Type: application/json
