@baseUrl = http://localhost:3000
@resource = auth

### LOGIN 
POST {{baseUrl}}/{{resource}}/login
Content-Type: application/json
  
  {
      "email": "johndoe@mail.com",
      "password": "Julianosis1234*"
  }


### GET PROFILE

GET {{baseUrl}}/{{resource}}/profile
Authorization: Bearer {{token}}
Content-Type: application/json
